export const products = [
  {
    id: 1,
    name: "DAMENSCH Statement Printed Crew TEES",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/81WrxjDEV8L._UX569_.jpg",
    price: 799,
  },
  {
    id: 2,
    name: "Dennis Lingo Men's Solid Slim Fit Cotton Casual Shirt with Spread Collar & Full Sleeves ",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/51yIybqYFTL._UL1100_.jpg",
    price: 1999,
  },
  {
    id: 3,
    name: "JUGULAR Men's Polyester Solid Men Stylish Cargo Track Pants",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/61IIKfT7AZL._UL1500_.jpg",
    price: 999,
  },
  {
    id: 4,
    name: "Puma Mens Coarse Running Shoe ",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/51Cs+xUnFNL._UL1200_.jpg",
    price: 2999,
  },
  {
    id: 5,
    name: "Nike Mens Air Force 1 '07 An20 Basketball Shoes",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/61ifQgbPetL._UL1500_.jpg",
    price: 2499,
  },
  {
    id: 6,
    name: "Hidesign Men's Western (Brown)",
    category: "Men's Clothing",
    image: "https://m.media-amazon.com/images/I/41tNZLbf9CL._UL1100_.jpg",
    price: 1499,
  },
  {
    id: 7,
    name: "SERA Women's Crepe A-Line Midi Dress ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/71YAC0PJPKL._UL1440_.jpg",
    price: 1299,
  },
  {
    id: 8,
    name: "Stylander Crop Top for Women, Crop Top for Girls, Womens Crop Top, Girls Crop Top, Crop Top (Style 1) ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/41axiiOzn+L._UL1439_.jpg",
    price: 1999,
  },
  {
    id: 9,
    name: "Lymio Dresses for Women || Western Dresses for Women || Dress for Women || Dresses (632) ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/81s3Bg2AaVL._UL1500_.jpg",
    price: 599,
  },
  {
    id: 10,
    name: "Miss Chase Women's Comfortable Round Neck Sleeveless Striped Midi Bodycon Dress with Zipper ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/815nD5rD+uL._UL1500_.jpg",
    price: 2999,
  },
  {
    id: 11,
    name: "Women Designer Handbags and Purses Ladies Satchel Bags Shoulder Bags Top Handle Bags w/Matching Wallet ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/61rgQ6pyPHL._UL1500_.jpg",
    price: 2499,
  },
  {
    id: 12,
    name: "WESTBRONCO Purses For Women Vegan Leather Purses and Handbags Large Ladies Tote Shoulder Bag ",
    category: "Women's Clothing",
    image: "https://m.media-amazon.com/images/I/615Q6zSGXnL._UL1001_.jpg",
    price: 2999,
  },
  {
    id: 13,
    name: "MAA SHAKTI GEMS Designer Jewellery Sets Pearl Moti Necklace Extremely Useful South Sea Fresh Water Beads Such Moti Ki Mala Certified By Reputed Lab For Women & Girls ",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/318liXtt2uL.jpg",
    price: 18999,
  },
  {
    id: 14,
    name: "American Diamond Bridal Choker Jewellery set for women ",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/71NkTTM-gjS._UL1440_.jpg",
    price: 65999,
  },
  {
    id: 15,
    name: "Candere By Kalyan Jewellers Yellow Gold Stud Earrings for Women ",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/61fBAXA6HYL._UL1100_.jpg",
    price: 2499,
  },
  {
    id: 16,
    name: "PH Artistic Choker Necklace Earring Set Radha Krishna 925 Sterling Silver Tribal Temple Jewelry Handmade Women Gift India W 741 ",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/41jd-25HUeL.jpg",
    price: 43999,
  },
  {
    id: 17,
    name: "Rajasthan Gems 925 Sterling Silver Natural Amethyst Ring Necklace Earrings Set 16.5 inch",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/511YlDCk4nL._UL1500_.jpg",
    price: 14999,
  },
  {
    id: 18,
    name: "PC Jeweller The Nyska 18KT Yellow Gold & Diamond Rings ",
    category: "Jewelry",
    image: "https://m.media-amazon.com/images/I/71+Bec2OXVL._UL1500_.jpg",
    price: 9999,
  },
  {
    id: 19,
    name: "HP Laserjet 138fnw Monochrome Compact Wi-Fi Printer with Network Support for Reliable, Fast Printing (Print, Copy, Scan, Fax) ",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/7167rMnsH1L._SL1500_.jpg",
    price: 24999,
  },
  {
    id: 20,
    name: "HP Pavilion 14 11th Gen Intel Core i5 16GB RAM/512GB SSD 14 inch (35.6cm) IPS Anti-Glare FHD Laptop/Intel Iris Xe Graphics/Backlit Kb/B&O Audio/FPR/Windows 11 Home/Thin & Light/1.41Kg, 14-Dv1001tu ",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71wvVy6sbuL._SX679_.jpg",
    price: 59999,
  },
  {
    id: 21,
    name: "HP Victus Gaming Laptop AMD Ryzen 5 5600H 15.6 inch(39.6 cm) FHD IPS Gaming Laptop (16GB RAM/512GB SSD/NVIDIA GeForce RTX 3050 4GB Graphics/144Hz/9ms Response time/Backlit KB/B&O/Alexa),15-fb0106AX",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/61yrJDgUKcL._SL1000_.jpg",
    price: 69999,
  },
  {
    id: 22,
    name: "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound, IPX7 Water Resistance, TWS Feature, Up to 12H Total Playtime, Multi-Compatibility Modes and Type-C Charging(Groovy Grey) ",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/61d3zo0hm9L._SL1500_.jpg",
    price: 3999,
  },
  {
    id: 23,
    name: "Zebronics ZEB-COUNTY 3W Wireless Bluetooth Portable Speaker With Supporting Carry Handle, USB, SD Card, AUX, FM & Call Function. (Green) ",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/81U3kN9bf1L._SL1500_.jpg",
    price: 24999,
  },
  {
    id: 24,
    name: "OnePlus 80 cm (32 inches) Y Series HD Ready LED Smart Android TV 32Y1 (Black) ",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71d5fMDvq9L._SL1500_.jpg",
    price: 79999,
  },
];
